about/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from about.views import DevInfoView
from about.views import AboutView

app_name = "about"

urlpatterns = [
    path("", AboutView.as_view(), name="about"),
    path("devinfo", DevInfoView.as_view(), name="devinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

exhibits/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from exhibits.views import ExhibitsListView
from exhibits.views import ExhibitsMainView
from exhibits.views import ExhibitsDetailView

app_name = "exhibits"

urlpatterns = [
    path("<slug>", ExhibitsDetailView.as_view(), name="exhibit_detail"),
    path(
        "", ExhibitsMainView.as_view(),
        name="exhibit_main"
    ),
    path(
        "exhibit_list/<museum_slug>", ExhibitsListView.as_view(),
        name="exhibit_list"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

group_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("exhibits/", include("exhibits.urls")),
    path("museums/", include("museums.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

homepage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.CityFormHPClass.as_view(), name="home"),
    path("<city_slug>", views.HPEventsView.as_view(), name="homepage_events"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

museums/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from museums import views

app_name = "museums"

urlpatterns = [
    path("<slug>/", views.MuseumDetailView.as_view(), name="museum_detail"),
    path("", views.MuseumListView.as_view(), name="museum_list"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<div class="container" style="clear: both;">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link px-2 text-muted">Главная</a></li>
        <li class="nav-item"><a href="{% url 'museums:museum_list' %}" class="nav-link px-2 text-muted">Музеи</a></li>
        <li class="nav-item"><a href="{% url 'exhibits:exhibit_main' %}" class="nav-link px-2 text-muted">Экспонаты</a></li>
        <li class="nav-item"><a href="{% url 'about:about' %}" class="nav-link px-2 text-muted">Про проект</a></li>
        <li class="nav-item"><a href="https://github.com/hecker0makhambet" class="nav-link px-2 text-muted">Махамбет</a></li>
        <li class="nav-item"><a href="https://github.com/visill" class="nav-link px-2 text-muted">Виктор(тимлид)</a></li>
        <li class="nav-item"><a href="https://github.com/Egor-05" class="nav-link px-2 text-muted">Егор</a></li>
      </ul>
      
      <p class="text-center text-muted">&copy; 2022 Makhambet & Victor & Egor, Inc</p>
    </footer>
</div>

templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a style="margin-left: 10px;" class="navbar-brand" href="{% url 'homepage:home' %}"><img width="32px" height="32px" src="{% static 'favicon.png' %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% with request.resolver_match.view_name as view_name %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if view_name == 'homepage:home' %}active{% endif %}">
        <a class="nav-link" {% if view_name != 'homepage:home' %}href="{% url 'homepage:home' %}"{% endif %}>Главная</a>
      </li>
      <li class="nav-item {% if view_name == 'museums:museum_list' %}active{% endif %}">
        <a class="nav-link" {% if view_name != 'museums:museum_list' %}href="{% url 'museums:museum_list' %}"{% endif %}>Музеи</a>
      </li>
      <li class="nav-item {% if view_name == 'exhibits:exhibit_main' %}active{% endif %}">
        <a class="nav-link" {% if view_name != 'exhibits:exhibit_main' %}href="{% url 'exhibits:exhibit_main' %}"{% endif %}>Экспонаты</a>
      </li>
      <li class="nav-item {% if view_name == 'about:about' %}active{% endif %}">
        <a class="nav-link" {% if view_name != 'about:about' %}href="{% url 'about:about' %}"{% endif %}>Про проект</a>
      </li>
      <li class="nav-item {% if view_name == 'about:devinfo' %}active{% endif %}">
        <a class="nav-link" {% if view_name != 'about:devinfo' %}href="{% url 'about:devinfo'%}"{% endif %}>Про техническую часть</a>
      </li>
    </ul>
  </div>
  {% endwith %}
</nav>