about/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from about.views import DevInfoView
from about.views import AboutView

app_name = "about"

urlpatterns = [
    path("", AboutView.as_view(), name="about"),
    path("devinfo", DevInfoView.as_view(), name="devinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

exhibits/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from exhibits.views import ExhibitsListView
from exhibits.views import ExhibitsMainView
from exhibits.views import ExhibitsDetailView

app_name = "exhibits"

urlpatterns = [
    path("<slug>", ExhibitsDetailView.as_view(), name="exhibit_detail"),
    path(
        "", ExhibitsMainView.as_view(),
        name="exhibit_main"
    ),
    path(
        "exhibit_list/<museum_slug>", ExhibitsListView.as_view(),
        name="exhibit_list"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

group_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("exhibits/", include("exhibits.urls")),
    path("museums/", include("museums.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

museums/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from museums import views

app_name = "museums"

urlpatterns = [
    path("<slug>/", views.MuseumDetailView.as_view(), name="museum_detail"),
    path("", views.MuseumListView.as_view(), name="museum_list"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

exhibits/models.py
from django.db import models

from core.models import BaseModelWithImage
from museums.models import Museum


class Exhibit(BaseModelWithImage):
    museum = models.ForeignKey(
        Museum,
        on_delete=models.CASCADE,
        related_name="exhibits",
        verbose_name="музей, к которому принадлежит этот экспонат",
    )

    class Meta:
        verbose_name = "экспонат"
        verbose_name_plural = "экспонаты"

    def __str__(self):
        return self.name

exhibits/forms.py
from django import forms

from museums.models import Museum
from homepage.utils import is_migration


class MuseumChoiceForm(forms.Form):
    museums = []
    if not is_migration():
        museums = [(i.slug, i.name) for i in Museum.objects.all()]

    museum = forms.ChoiceField(
        choices=museums,
        label="Выберите музей, экспонаты которого вы хотите видеть"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control form-select"

exhibits/views.py
from django.urls import reverse
from django.views.generic import FormView
from django.views.generic import DetailView
from django.views.generic import TemplateView

from exhibits.models import Exhibit
from exhibits.forms import MuseumChoiceForm


class ExhibitsMainView(FormView):
    form_class = MuseumChoiceForm
    template_name = "exhibit/main.html"

    def form_valid(self, form):
        self.slug = form.cleaned_data["museum"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('exhibits:exhibit_list', args=[self.slug])


class ExhibitsDetailView(DetailView):
    model = Exhibit
    template_name = "exhibit/detail.html"
    context_object_name = "exhibit"


class ExhibitsListView(TemplateView):
    template_name = "exhibit/list.html"

    def get(self, response, *args, **kwargs):
        context = {
            "exhibits": (
                Exhibit.objects.filter(museum__slug=kwargs["museum_slug"])
            )
        }
        return self.render_to_response(context)

templates/exhibit/detail.html
{% extends 'base.html' %}

{% block content %}
<div style="" class="main">
  <div>
  <img src="{{ exhibit.image.url }}"
  style="margin-bottom: 15px;" width="300px" height="300px"></div>
  <div class="alert alert-primary">Название: {{ exhibit.name }}</div>
  <div class="alert alert-secondary">Описание: {{ exhibit.description|safe }}</div>
  <div class="alert alert-danger">Музей: {{ exhibit.museum.name }} <a href="{% url 'museums:museum_detail' exhibit.museum.slug %}">Подробнее...</a></div>
</div>
{% endblock %}

templates/exhibit/exhibit_card.html
<div class="card mb-3" style="width:300px; height:500px; margin: 20px; float: left;">
  <img class="card-img-top" width="300px" height="300px"  src="{{ exhibit.image.url }}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><a href="{% url 'exhibits:exhibit_detail' exhibit.slug %}">{{ exhibit.name }}</a></h5>
  </div>
</div>

templates/exhibit/list.html
{% extends 'base.html' %}

{% block content %}
{% for exhibit in exhibits %}
  {% include 'exhibit/exhibit_card.html' %}
  {% if forloop.counter0 > 0 and forloop.counter0|divisibleby:"4" %}
  <div style="margin:650px;"> <hr></div>
  {% endif %}
{% empty %}
Похоже, этот музей сейчас без экспонатов. Загляните в другое время!)
{% endfor %}
{% endblock %}

templates/exhibit/main.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-3">
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
    {% for field in form %}
    <div class="row g-3 align-items-center">
            <div class="col-sm-2">
                {{ field.label_tag }}
            </div>
            <div class="col-sm-10">
                {{ field }}
            </div>
        </div>
    </div>
{% endfor %}
<button type="submit" class="btn btn-primary">Отправить</button>
</form>
</div>
<hr>
<h3>Здравствуйте, мы рады приветствовать Вас на нашем сайте-агрегаторе музеев.<br>
    Здесь Вы сможете:<br>Посмотреть на экспонаты музея в онлайн формате<br>Узнать актуальные новости музеев Вашего города<br>Посмотреть новости конкретного музея</h3>


{% endblock %}