about/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from about.views import DevInfoView
from about.views import AboutView

app_name = "about"

urlpatterns = [
    path("", AboutView.as_view(), name="about"),
    path("devinfo", DevInfoView.as_view(), name="devinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

exhibits/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from exhibits.views import ExhibitsListView
from exhibits.views import ExhibitsMainView
from exhibits.views import ExhibitsDetailView

app_name = "exhibits"

urlpatterns = [
    path("<slug>", ExhibitsDetailView.as_view(), name="exhibit_detail"),
    path(
        "", ExhibitsMainView.as_view(),
        name="exhibit_main"
    ),
    path(
        "exhibit_list/<museum_slug>", ExhibitsListView.as_view(),
        name="exhibit_list"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

group_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("exhibits/", include("exhibits.urls")),
    path("museums/", include("museums.urls")),
    path("events/", include("events.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

museums/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from museums import views

app_name = "museums"

urlpatterns = [
    path("<slug>/", views.MuseumDetailView.as_view(), name="museum_detail"),
    path("", views.MuseumListView.as_view(), name="museum_list"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

museums/models.py
from django.db import models

from core.models import BaseModelWithImage


class CityManager(models.Manager):
    def get_city_by_slug(slug):
        return City.objects.get(slug=slug)


class City(models.Model):
    name = models.CharField("название города", max_length=168)
    slug = models.CharField("уникальный слаг(путь) города", max_length=150)

    objects = CityManager()

    class Meta:
        verbose_name = "город"
        verbose_name_plural = "города"

    def __str__(self):
        return self.name


class Museum(BaseModelWithImage):
    address = models.TextField("адрес музея", blank=True)
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        related_name="museums",
        verbose_name="город, в котором расположен текущий музей",
    )

    class Meta:
        verbose_name = "музей"
        verbose_name_plural = "музеи"

    def __str__(self):
        return self.name

museums/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from museums.models import Museum


class MuseumDetailView(TemplateView):
    template_name = "museum/detail.html"

    def get(self, request, *args, **kwargs):
        museum = get_object_or_404(Museum, slug=kwargs["slug"])
        events = museum.events.order_by("date")
        context = {"museum": museum, "events": events}
        return self.render_to_response(context)


class MuseumListView(TemplateView):
    template_name = "museum/list.html"

    def get(self, request, *args, **kwargs):
        city_museum = {}

        for i in Museum.objects.all():
            if i.city not in list(city_museum.keys()):
                city_museum[i.city] = []
            city_museum[i.city].append(i)
        context = {"museums": city_museum}
        return self.render_to_response(context)

templates/museum/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-3">
      <img class="img-fluid rounded-start" width="300" height="300" src="{{ museum.image.url }}" alt="Card image cap">
    </div>
    <div class="col-md-9">
      <div class="card-body">
        <h5 class="card-title">{{ museum.name }}</h5>
        <p class="card-text">Описание:<br>{{ museum.description|safe }}</p>
        <p class="card-text">Адрес:<br>{{ museum.address }}</p>
        <p class="card-text">Ссылка на сайт:<br><a href="{{ museum.link }}">{{ museum.link }}</a></p>
        <a href="{% url 'exhibits:exhibit_list' museum.slug %}" role="button" class="btn btn-outline-primary">Перейти к просмотру экспонатов этого музея</a>
      </div>
    </div>
  </div>
  <div>
    <hr>
    <h2>Новости музея:</h2>
    {% for event in events %}
      <br>
      {% include 'events/event_card.html' %}
      {% endfor %}
    </div>
</div>
{% endblock %}

templates/museum/list.html
{% extends "base.html" %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Город</th>
      <th scope="col">Адрес</th>
    </tr>
  </thead>
  <tbody>
  {% for city, museum in museums.items %}
    {% for museum in museum %}
      <tr>
        <td><a href="{% url 'museums:museum_detail' museum.slug %}">{{ museum.name }}</a></td>
        <td><strong>{{ city }}</strong></td>
        <td>{{ museum.address }}</td>
      </tr>
    {% endfor %}
  {% endfor %}
  </tbody>
</table>
{% endblock %}